services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PGHOST=postgres_db
      - PGPORT=5432
      - PGUSER=test
      - PGPASSWORD=test
      - PGDATABASE=db
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=db
